### PR TITLE
Icehouse yaml

### PR DESCRIPTION
**Pull request by Akilesh1597**

### CODE REVIEW

**Comment by UtahDave** [comment]
This is great!  Would it be difficult to update the json examples in the README.md to use yaml as well?

**Comment by Akilesh1597** [comment]
The earliest I can do that is next Monday. Got loads of work on high
priority.

**Comment by EntropyWorks** [comment]
I may have a README.md ...
https://github.com/EntropyWorks/openstack-automation/blob/yaml/README.md

BTW thank you for adding yaml support!

**Comment by Akilesh1597** [comment]
Readme is yaml but I have changed certain things in icehouse installation and it doesn't reflect those. I'll see into this.

**Pull request merged**
