### PR TITLE
Remove OS generated ~ files

### PR DESCRIPTION
**Pull request by fritzstauff**
Removed duplicate OS generated files with trailing ~.

### CODE REVIEW

**Comment by theY4Kman** [comment]
selfie-1

**Comment by jasonkeene** [comment]
Wow, this is what I've always wanted. Thank you soo much @fritzstauff you are a saint!
giphy

**Comment by exit99** [comment]
kanyeclap
Wow just perfect.

**Comment by erronjason** [comment]
My baby is growin up. Oh here come the vapors
selfie-2

**Comment by jasonkeene** [comment]
Fly baby bird fly!
tumblr_mfosuciwi51r7w8cbo1_500

**Comment by Nick011** [comment]
LGTM

**Pull request merged**
